# Docker-compose file alows us to run the docker image easily from  our project location
# It allows us to manage the different services that makeup our project 
# EX: one service might be the python and other might be the database
version: "3"

services: 
    app:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"